//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_BITMAP5                     159
#define IDB_BITMAP7                     162
#define STAGE_TWENTYONE_SL              162
#define MY_HOMEPAGE                     165
#define MY_LEADER                       169
#define MY_BOX                          170
#define MY_FLOOR                        171
#define MY_LEADER_DOWN                  172
#define MY_LEADER_LEFT                  173
#define MY_LEADER_RIGHT                 174
#define MY_LEADER_UP                    175
#define MY_STAGE_ONE                    176
#define LEADER_DOWN                     177
#define LEADER_LEFT                     178
#define LEADER_RIGHT                    179
#define IDB_BITMAP11                    180
#define LEADER_UP                       180
#define IDB_BITMAP10                    181
#define MY_STAGE_TWO                    181
#define MY_STAGE_THREE                  183
#define MY_STAGE_FOUR                   184
#define STAGE_ONE_CP                    186
#define STAGE_ONE_SL                    187
#define IDB_BITMAP9                     188
#define STAGE_TWO_SL                    189
#define IDB_BITMAP12                    190
#define STAGE_TWO_CP                    190
#define STAGE_THREE_CP                  192
#define STAGE_FOUR_CP                   193
#define STAGE_THREE_SL                  194
#define STAGE_FOUR_SL                   195
#define STAGE_FIVE_CP                   198
#define STAGE_SIX_CP                    199
#define STAGE_SEVEN_CP                  200
#define STAGE_FIVE_SL                   201
#define STAGE_SIX_SL                    202
#define STAGE_SEVEN_SL                  203
#define STAGE_EIGHT_SL                  204
#define MY_STAGE_FIVE                   205
#define MY_STAGE_SIX                    206
#define MY_STAGE_SEVEN                  207
#define IDB_BITMAP13                    208
#define RED_LINE                        208
#define IDB_BITMAP15                    211
#define STAGE_ONE_BOTTOM_LEFT           211
#define LEFT_CIRCLE                     211
#define RIGHT_CIRCLE                    211
#define IDB_BITMAP16                    212
#define STAGE_ONE_BOTTOM_RIGHT          212
#define HAND_CIRCLE                     212
#define IDB_BITMAP17                    215
#define MY_DIRECTION                    215
#define MY_STAGE_EIGHT                  216
#define STAGE_EIGHT_CP                  217
#define STAGE_NINE_SL                   218
#define STAGE_NINE_CP                   219
#define STAGE_TEN_CP                    220
#define STAGE_ELEVEN_CP                 221
#define STAGE_TEN_SL                    222
#define STAGE_ELEVEN_SL                 223
#define MY_STAGE_NINE                   225
#define MY_STAGE_TEN                    226
#define MY_STAGE_ELEVEN                 227
#define STAGE_TWELVE_SL                 228
#define STAGE_TWELVE_CP                 238
#define STAGE_THIRTEEN_CP               239
#define STAGE_FOURTEEN_CP               240
#define STAGE_THIRTEEN_SL               241
#define STAGE_FOURTEEN_SL               242
#define STAGE_FIFTEEN_SL                243
#define MY_STAGE_TWELVE                 244
#define MY_STAGE_THIRTEEN               245
#define IDB_BITMAP25                    246
#define MY_STAGE_FOURTEEN               246
#define IDB_BITMAP14                    247
#define MY_BOX_CHECK                    247
#define SELECT_BG                       248
#define IDB_BITMAP18                    249
#define SELECT_ALL_LOCK                 249
#define STAGE_FIFTEEN_CP                250
#define STAGE_SIXTEEN_CP                251
#define STAGE_SEVENTEEN_CP              252
#define STAGE_THIRTY_SL                 253
#define MY_STAGE_FIFTEEN                254
#define MY_STAGE_SIXTEEN                255
#define MY_STAGE_SEVENTEEN              256
#define STAGE_SIXTEEN_SL                257
#define STAGE_SEVENTEEN_SL              258
#define IDB_BITMAP21                    259
#define STAGE_EIGHTEEN_SL               259
#define STAGE_EIGHTEEN_CP               261
#define STAGE_NINETEEN_CP               262
#define STAGE_TWENTY_CP                 263
#define STAGE_TWENTYONE_CP              264
#define STAGE_TWEMTYTWO_CP              265
#define STAGE_TWENTYTWO_CP              265
#define STAGE_TWENTYTHREE_CP            266
#define STAGE_TWENTYFOUR_CP             267
#define STAGE_TWENTYFIVE_CP             268
#define STAGE_TWENTYSIX_CP              269
#define STAGE_TWENTYSEVEN_CP            270
#define STAGE_TWENTYEIGHT_CP            271
#define STAGE_TWENTYNINE_CP             272
#define MY_STAGE_EIGHTEEN               273
#define MY_STAGE_NINETEEN               274
#define MY_STAGE_TWENTY                 275
#define MY_STAGE_TWENTYONE              276
#define MY_STAGE_TWENTYTWO              277
#define MY_STAGE_TWENTYTHREE            278
#define MY_STAGE_TWENTYFOUR             279
#define MY_STAGE_TWENTYFIVE             280
#define MY_STAGE_TWENTYSIX              281
#define MY_STAGE_TWENTYSEVEN            282
#define MY_STAGE_TWENTYEIGHT            283
#define MY_STAGE_TWENTYNINE             284
#define STAGE_NINETEEN_SL               286
#define STAGE_TWENTY_SL                 287
#define STAGE_TWENTYTWO_SL              289
#define STAGE_TWENTYTHREE_SL            290
#define STAGE_TWENTYFOUR_SL             291
#define STAGE_TWENTYFIVE_SL             292
#define STAGE_TWENTYSIX_SL              293
#define STAGE_TWENTYSEVEN_SL            294
#define STAGE_TWENTYEIGHT_SL            295
#define STAGE_TWENTYNINE_SL             296
#define IDB_BITMAP3                     299
#define INFO                            299
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        300
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
